build:
  cuda_version: "12.1.1"
  system_packages:
    - "libgl1-mesa-glx"
  run:
    - "git clone https://github.com/rbgo404/segment-anything-2.git"
    - "cd segment-anything-2"
    - "pip install -e ."
